seed: 3407
task: 'va'


train_data:
  name: 'SequenceData'
  args:
    feat_root: '/data/ABAW5/Aff-Wild2/feat/'
    label_root: '/data/ABAW5/Aff-Wild2/annotations/VA_Estimation_Challenge/Train_Set'
    seq_len: 150
    task: 'va'
    pad_mode: 'repeat_last'
    feat_dict:
      fau: 512
      ires100_7_expr: 512
      ecapatdnn: 512
      hubert: 512

val_data:
  name: 'SequenceData'
  args:
    feat_root: '/data/ABAW5/Aff-Wild2/feat/'
    label_root: '/data/ABAW5/Aff-Wild2/annotations/VA_Estimation_Challenge/Validation_Set'
    seq_len: 150
    task: 'va'
    pad_mode: 'repeat_last'
    feat_dict:
      fau: 512
      ires100_7_expr: 512
      ecapatdnn: 512
      hubert: 512

dataloader:
  batch_size: 16
  num_workers: 4
  pin_memory: true
  collate_fn: 'base_collate_fn'

model:
  name: 'BERT'
  args:
    input_dim: 2048
    feedforward_dim: 1024
    affine_dim: 1024
    nheads: 4
    nlayers: 4
    dropout: 0.3
    use_pe: True
    seq_len: 150
    head_dropout: 0.1
    head_dims:
      - 512
      - 256
    out_dim: 1
    task: 'va'

solver:
  name: 'BaseSolver'
  args:
    epoch: 25

  optimizer:
    name: 'Adam'
    args:
      lr: !!float 5e-5
      weight_decay: !!float 1e-5

  lr_scheduler:
    name: 'StepLR'
    args:
      step_size: 20
      gamma: 0.1

  loss:
    name: 'VALoss'
    args:
      eps: !!float 1e-8

  logger:
    log_root: '/data/abaw5/log/'
    suffix: 'va'

  metric:
    name: 'VAMetric'
